 #Turtle Artist
#Auther: Nishaan Gill
#October 30

#We are drawing a soccer ball
#
import turtle

def draw_ellipse(rad):
    # Draw the first part of the ellipse
    turtle.circle(rad, 90)
    turtle.circle(rad // 2, 90)
    # Draw the second part of the ellipse
    turtle.circle(rad, 90)
    turtle.circle(rad // 2, 90)

#Set up screen
wn = turtle.Screen()
wn.bgcolor("lightblue")

pen = turtle.Turtle()
pen.speed(0)
pen.pensize(2)

# Fuction to draw a circle
# pen.begin_fill()
# pen.color("white")
# pen.circle(100)
# pen.end_fill()
# pen.up()


pen.penup()
pen.goto(-50, 100)
pen.pendown()
# Function to draw hexagon
pen.fillcolor("black")
pen.begin_fill()
pen.setheading(270)
pen.color("black")
pen.down()
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.end_fill()

pen.penup()

pen.goto(75, 100)
pen.pendown()
# Function to draw hexagon
pen.setheading(270)
pen.color("black")
pen.down()
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.end_fill()

pen.penup()
pen.goto(75,-20)
pen.pendown()
# Function to draw hexagon
pen.setheading(270)
pen.color("black")
pen.down()
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.end_fill()

pen.penup()
pen.goto(-50,-20)
pen.pendown()
# Function to draw hexagon
pen.setheading(270)
pen.color("black")
pen.down()
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.left(45)
pen.forward(50)
pen.end_fill()

# pen.goto(-25, 100)
# # Function to draw hexagon
# pen.setheading(270)
# pen.color("black")
# pen.down()
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.left(45)
# pen.forward(50)
# pen.end_fill()

wn.exitonclick()
